

DiningPhilosophers:
	g++ src/DiningPhilosophers.cpp -o bin/diningphilosophers -pthread -std=c++11
	./bin/diningphilosophers
MutualExclusion:
	g++ src/MutualExclusion.cpp -o bin/mutualexclusion -pthread -std=c++11
	./bin/mutualexclusion
ProducersConsumers:
	g++ src/ProducersConsumers.cpp -o bin/producersconsumers -pthread -std=c++11
	./bin/producersconsumers
ReadersWriters:
	g++ src/ReadersWriters.cpp -o bin/readerswriters -pthread -std=c++11
	./bin/readerswriters
